# Generated by Django 3.1 on 2020-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shift',
            table='shift',
        ),
        migrations.AlterModelTable(
            name='shiftcode',
            table='shift_code',
        ),
    ]
