# Generated by Django 3.1 on 2020-09-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_id', to='shift.shiftcode'),
        ),
    ]
