# Generated by Django 3.1 on 2020-09-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField()),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_id', to='category.category', verbose_name='Category Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_update', to=settings.AUTH_USER_MODEL, verbose_name='Update by')),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Category 2 Translation')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_id', to='checklist.checklist')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_translation_language', to='language.language', verbose_name='Language ID')),
            ],
            options={
                'db_table': 'checklist_translation',
            },
        ),
    ]
