# Generated by Django 3.1 on 2020-09-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200930_0038'),
        ('checklist', '0003_auto_20200930_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_category', to='category.categorytranslation', verbose_name='Category Name'),
        ),
    ]
