# Generated by Django 3.1 on 2020-09-30 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField()),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_update', to=settings.AUTH_USER_MODEL, verbose_name='Update by')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Translation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_translation', to='category.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_category_id', to='language.language', verbose_name='Language ID')),
            ],
            options={
                'db_table': 'category_translation',
            },
        ),
    ]
