# Generated by Django 3.1 on 2020-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1',
            name='created_by',
            field=models.CharField(max_length=100, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='category1',
            name='update_by',
            field=models.CharField(max_length=100, verbose_name='Update by'),
        ),
    ]
