# Generated by Django 3.1 on 2020-09-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='categoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='category.category1', verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category3',
            name='categoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_codes', to='category.category1', verbose_name='Category Name'),
        ),
    ]
