# Generated by Django 3.1 on 2020-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
