# Generated by Django 3.1 on 2020-09-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200911_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='categoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist', to='category.category1', verbose_name='Category Name'),
        ),
    ]
