# Generated by Django 3.1 on 2020-09-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200915_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category3',
            old_name='categoryName',
            new_name='categoryID',
        ),
    ]
