# Generated by Django 3.1 on 2020-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_no',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
