# Generated by Django 3.1 on 2020-09-24 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0002_auto_20200925_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defectcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_codes_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_codes_update', to=settings.AUTH_USER_MODEL, verbose_name='Update by')),
            ],
            options={
                'db_table': 'defect_codes',
            },
        ),
        migrations.CreateModel(
            name='DefectcodesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category 3 Translation')),
                ('defect_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_codes_id', to='defect_codes.defectcodes')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_codes_language', to='language.language', verbose_name='Language ID')),
            ],
            options={
                'db_table': 'defect_codes_translations',
            },
        ),
    ]
