# Generated by Django 3.1 on 2020-09-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defect_codes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectcodestranslation',
            name='defect_codes',
        ),
        migrations.AddField(
            model_name='defectcodestranslation',
            name='defect_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_code_id', to='defect_codes.defectcodes'),
        ),
    ]
