# Generated by Django 3.1 on 2020-09-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defect_codes', '0002_auto_20200930_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectcodestranslation',
            name='defect_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_code_translation', to='defect_codes.defectcodes'),
        ),
    ]
