# Generated by Django 3.1 on 2020-09-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect_codes', '0004_auto_20200930_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectcodes',
            name='description',
        ),
    ]
