# Generated by Django 3.1 on 2020-09-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defect_codes', '0005_remove_defectcodes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectcodestranslation',
            name='defect_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defect_code_translation', to='defect_codes.defectcodes'),
            preserve_default=False,
        ),
    ]
