# Generated by Django 3.1 on 2020-09-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect_codes', '0006_auto_20200930_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectcodestranslation',
            old_name='descriptions',
            new_name='description',
        ),
    ]
